
project_id = "alreeczvrvcruvxoxhvh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
bucket_definitions = [
  { name = "services", public = true, file_size_limit = "5mb", allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp"] }
]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
